// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzFjWPKdbqvIapOyRWwy1-kjoyH4durFE',
    appId: '1:97468882781:web:61539953f1f6675c2b52b4',
    messagingSenderId: '97468882781',
    projectId: 'trackflix-17998',
    authDomain: 'trackflix-17998.firebaseapp.com',
    storageBucket: 'trackflix-17998.firebasestorage.app',
    measurementId: 'G-G9SKZY8ZG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZgvnQFSpm9ZB3hfg5QQwtcWzHO55teo4',
    appId: '1:97468882781:android:943032eac02451972b52b4',
    messagingSenderId: '97468882781',
    projectId: 'trackflix-17998',
    storageBucket: 'trackflix-17998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6rAfOdiCdyYDb7BNBq5uw0cW7aJsnZtY',
    appId: '1:97468882781:ios:ee66eeeb4b12003e2b52b4',
    messagingSenderId: '97468882781',
    projectId: 'trackflix-17998',
    storageBucket: 'trackflix-17998.firebasestorage.app',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6rAfOdiCdyYDb7BNBq5uw0cW7aJsnZtY',
    appId: '1:97468882781:ios:ee66eeeb4b12003e2b52b4',
    messagingSenderId: '97468882781',
    projectId: 'trackflix-17998',
    storageBucket: 'trackflix-17998.firebasestorage.app',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzFjWPKdbqvIapOyRWwy1-kjoyH4durFE',
    appId: '1:97468882781:web:2b9700ba031d2d4f2b52b4',
    messagingSenderId: '97468882781',
    projectId: 'trackflix-17998',
    authDomain: 'trackflix-17998.firebaseapp.com',
    storageBucket: 'trackflix-17998.firebasestorage.app',
    measurementId: 'G-5K57KBFW7Q',
  );

}